"use client";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from "@tanstack/react-query";
import { flexRender, getCoreRowModel, useReactTable, type ColumnDef, type RowSelectionState, type VisibilityState } from "@tanstack/react-table";
import { ArrowDownToLine, ArrowLeft, ArrowUpRight, Check, ChevronLeft, ChevronRight, CircleHelp, Columns3, Copy, Database, FileText, Filter, LayoutDashboard, LoaderCircle, LockKeyhole, LogOut, Mail, Menu, RefreshCw, Search, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { ADMIN_TABLES, EMPTY_FILTERS, fieldLabel, type AdminFilters, type AdminRow, type AdminTable, type RecordsResult } from "../../lib/admin/schema";
import { demoRecords } from "../../lib/admin/demo";
import { leadBrief, smartFilter } from "../../lib/admin/insights";
import { downloadWorkbook } from "../../lib/admin/export";
type Props = { configured: boolean; demoEnabled: boolean };
type Counts = { key: string; total: number | null; error: string | null }[];
class RequestError extends Error { constructor(message: string, readonly status: number) { super(message); } }
async function api<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`/api/admin/${path}`, { ...init, credentials: "same-origin", cache: "no-store", headers: { ...(init.body ? { "content-type": "application/json" } : {}), ...init.headers } }); const body = await response.json(); if (!response.ok) throw new RequestError(body.message || "Unable to complete this request.", response.status); return body as T; }
function queryString(table: AdminTable, filters: AdminFilters, offset = 0, limit = 25) { return new URLSearchParams({ table: table.key, ...filters, offset: String(offset), limit: String(limit) }); }
function filterDemo(rows: AdminRow[], table: AdminTable, filters: AdminFilters) { return rows.filter(row => (!filters.status || row.status === filters.status) && (!filters.search || table.search.some(key => String(row[key] || "").toLowerCase().includes(filters.search.toLowerCase()))) && (!filters.from || String(row[table.date]).slice(0, 10) >= filters.from) && (!filters.to || String(row[table.date]).slice(0, 10) <= filters.to)).sort((a, b) => (String(a[table.date]).localeCompare(String(b[table.date])) || String(a.id).localeCompare(String(b.id))) * (filters.sort === "oldest" ? 1 : -1)); }
function display(value: unknown) { return value === null || value === undefined || value === "" ? "—" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value); }
function dateLabel(value: unknown) { return value && Number.isFinite(Date.parse(String(value))) ? new Date(String(value)).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }) : "—"; }
function Brand() { return <a className="admBrand" href="/" aria-label="TruePrint home"><img src="/logo-blue-gradient.svg" width="32" height="34" alt="" /><span>trueprint<span className="admBrandDot">.</span></span></a>; }
function Status({ value }: { value: unknown }) { return <span className={`admStatus admStatus-${String(value)}`}><i />{display(value)}</span>; }
function Modal({ children, onClose, title, drawer = false }: { children: React.ReactNode; onClose: () => void; title: string; drawer?: boolean }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { ref.current?.showModal(); const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, []); return <dialog ref={ref} className={`admModal ${drawer ? "admDrawer" : ""}`} aria-label={title} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === ref.current) onClose(); }}><div className="admModalInside"><div className="admModalHead"><h2>{title}</h2><button className="admIcon" aria-label="Close dialog" onClick={onClose}><X size={20} /></button></div>{children}</div></dialog>; }
export default function AdminDashboard(props: Props) { const [client] = useState(() => new QueryClient({ defaultOptions: { queries: { retry: false, refetchOnWindowFocus: false, gcTime: 0 } } })); return <QueryClientProvider client={client}><Dashboard {...props} /></QueryClientProvider>; }

function Dashboard({ configured, demoEnabled }: Props) {
  const client = useQueryClient(); const [demo, setDemo] = useState(false); const [sampleRows, setSampleRows] = useState<Record<string, AdminRow[]>>({}); const [tableKey, setTableKey] = useState(ADMIN_TABLES[0].key); const table = ADMIN_TABLES.find(t => t.key === tableKey)!;
  const [filters, setFilters] = useState<AdminFilters>({ ...EMPTY_FILTERS }); const [search, setSearch] = useState(""); const [pagination, setPagination] = useState({ pageIndex: 0, pageSize: 25 }); const [selection, setSelection] = useState<RowSelectionState>({}); const [visible, setVisible] = useState<VisibilityState>({}); const [detail, setDetail] = useState<AdminRow | null>(null); const [menu, setMenu] = useState(false); const [exportOpen, setExportOpen] = useState(false); const [exportProgress, setExportProgress] = useState(""); const exportAbort = useRef<AbortController | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [loginBusy, setLoginBusy] = useState(false); const [assistant, setAssistant] = useState(""); const [help, setHelp] = useState(false);
  const session = useQuery({ queryKey: ["admin-session"], queryFn: async () => { try { return await api<{ user: { email: string } | null }>("session"); } catch (err) { if (err instanceof RequestError && [401,403,503].includes(err.status)) return { user: null }; throw err; } }, enabled: configured && !demo, staleTime: 30_000 });
  const user = session.data?.user; const active = demo || !!user;
  const overview = useQuery({ queryKey: ["admin-overview", demo], queryFn: ({ signal }) => api<{ tables: Counts }>("overview", { signal }), enabled: active && !demo, staleTime: 20_000 });
  const records = useQuery({ queryKey: ["admin-records", tableKey, filters, pagination, demo], queryFn: ({ signal }) => api<RecordsResult>(`records?${queryString(table, filters, pagination.pageIndex * pagination.pageSize, pagination.pageSize)}`, { signal }), enabled: active && !demo });
  const sampleFiltered = useMemo(() => filterDemo(sampleRows[tableKey] || [], table, filters), [sampleRows, tableKey, table, filters]);
  const rows = useMemo(() => demo ? sampleFiltered.slice(pagination.pageIndex * pagination.pageSize, (pagination.pageIndex + 1) * pagination.pageSize) : records.data?.rows || [], [demo, sampleFiltered, pagination, records.data]); const total = demo ? sampleFiltered.length : records.data?.total || 0; const counts = demo ? ADMIN_TABLES.map(t => ({ key: t.key, total: sampleRows[t.key]?.length || 0, error: null })) : overview.data?.tables || []; const available = counts.filter(t => t.total !== null).length; const allCount = counts.reduce((sum, t) => sum + (t.total || 0), 0); const pending = rows.filter(row => ["new", "incomplete"].includes(String(row.status))).length; const busy = !demo && records.isFetching;
  useEffect(() => { const timer = setTimeout(() => { setFilters(f => f.search === search ? f : { ...f, search }); setPagination(p => p.pageIndex ? { ...p, pageIndex: 0 } : p); }, 300); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { setSelection({}); }, [tableKey, filters, pagination]);
  useEffect(() => { const err = records.error || overview.error; if (err instanceof RequestError && [401,403].includes(err.status)) { exportAbort.current?.abort(); setDetail(null); setError(err.message); client.setQueryData(["admin-session"], { user: null }); client.removeQueries({ queryKey: ["admin-records"] }); client.removeQueries({ queryKey: ["admin-overview"] }); } }, [records.error, overview.error, client]);
  useEffect(() => () => { exportAbort.current?.abort(); }, []);
  function changeTable(key: string) { setTableKey(key); setFilters({ ...EMPTY_FILTERS }); setSearch(""); setPagination(p => ({ ...p, pageIndex: 0 })); setSelection({}); setVisible({}); setDetail(null); setError(""); setNotice(""); setMenu(false); window.scrollTo({ top:0, behavior:"instant" }); }
  function changeFilter(patch: Partial<AdminFilters>) { setFilters(f => ({ ...f, ...patch })); setPagination(p => ({ ...p, pageIndex: 0 })); }
  async function signIn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setLoginBusy(true); const form = new FormData(event.currentTarget); try { const data = await api<{ user: { email: string } }>("session", { method: "POST", body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); client.setQueryData(["admin-session"], data); } catch (err) { setError((err as Error).message); } finally { setLoginBusy(false); } }
  async function signOut() { exportAbort.current?.abort(); setError(""); try { if (!demo) await api("session", { method:"DELETE" }); await client.cancelQueries(); client.clear(); setDemo(false); setSampleRows({}); setDetail(null); setExportOpen(false); setNotice(""); setSelection({}); setTableKey(ADMIN_TABLES[0].key); setFilters({ ...EMPTY_FILTERS }); setSearch(""); setAssistant(""); setVisible({}); setPagination({ pageIndex:0, pageSize:25 }); client.setQueryData(["admin-session"], { user:null }); } catch(err) { setError((err as Error).message); } }
  function applyAssistant(text = assistant) { const parsed = smartFilter(text); const target = ADMIN_TABLES.find(t => t.key === parsed.table) || table; if (parsed.filters.status && !target.statuses.includes(parsed.filters.status)) { setError(`“${parsed.filters.status}” is not a status in ${target.label.toLowerCase()}.`); return; } setTableKey(target.key); setFilters(parsed.filters); setSearch(parsed.filters.search); setPagination(p => ({ ...p, pageIndex:0 })); setSelection({}); setVisible({}); setNotice(parsed.explanation); setError(""); }
  const columns = useMemo<ColumnDef<AdminRow>[]>(() => [
    { id:"select", header:({table:g}) => <input type="checkbox" aria-label="Select all records on this page" checked={g.getIsAllPageRowsSelected()} onChange={g.getToggleAllPageRowsSelectedHandler()} />, cell:({row}) => <input type="checkbox" aria-label={`Select ${row.original.name}`} checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} />, enableHiding:false },
    { id:"contact", header:"Contact", cell:({row}) => <button className="admPerson" onClick={() => setDetail(row.original)}><span className="admAvatar">{String(row.original.name || "?").split(" ").map(x => x[0]).slice(0,2).join("")}</span><span><strong>{display(row.original.name)}</strong><small>{display(row.original.email)}</small></span></button>, enableHiding:false },
    { id:"request", header:table.kind === "catalogue" ? "Catalogue" : "Requirement", cell:({row}) => <div className="admRequestCell"><span>{display(row.original.requirement || row.original.catalogue_title)}</span><small>{display(row.original.organization || table.label)}</small></div> },
    { accessorKey:"status", header:"Status", cell:({getValue}) => <Status value={getValue()} /> }, { id:"received", header:"Received · UTC", cell:({row}) => <span className="admDate">{dateLabel(row.original[table.date])}</span> },
    ...table.columns.filter(key => !["name","email","status","requirement","catalogue_title",table.date].includes(key)).map(key => ({accessorKey:key, header:fieldLabel(key), cell:({getValue}:{getValue:()=>unknown}) => <span className="admRawValue">{display(getValue())}</span>})),
    { id:"open", header:"", cell:({row}) => <button className="admIcon" onClick={() => setDetail(row.original)} aria-label={`View ${row.original.name}`}><ArrowUpRight size={17}/></button>, enableHiding:false },
  ],[table]);
  const visibility = { ...Object.fromEntries(table.columns.filter(key => !["name","email","status","requirement","catalogue_title",table.date].includes(key)).map(key => [key,false])), ...visible };
  const grid = useReactTable({ data:rows, columns, getCoreRowModel:getCoreRowModel(), getRowId:row => String(row.id), manualPagination:true, rowCount:total, state:{ pagination, rowSelection:selection, columnVisibility:visibility }, onPaginationChange:setPagination, onRowSelectionChange:setSelection, onColumnVisibilityChange:update => setVisible(typeof update === "function" ? update(visibility) : update), enableRowSelection:true });
  async function exportData(mode:"filtered"|"selected"|"all") {
    const controller = new AbortController(); exportAbort.current = controller; setError(""); setExportProgress("Preparing workbook…");
    try { const sheets:{table:AdminTable;rows:AdminRow[]}[] = []; let exported = 0; const before = new Date().toISOString();
      for (const item of mode === "all" ? ADMIN_TABLES : [table]) { let result:AdminRow[] = []; const usedFilters = mode === "all" ? EMPTY_FILTERS : filters;
        if (mode === "selected") result = grid.getSelectedRowModel().rows.map(r => r.original); else if(demo) result = filterDemo(sampleRows[item.key] || [],item,usedFilters);
        else { let expected:number|null = null; const seen = new Set<string>(); while(true) { controller.signal.throwIfAborted(); const query = queryString(item,usedFilters,result.length,500); query.set("before",before); const page = await api<RecordsResult>(`records?${query}`,{signal:controller.signal}); if(expected === null) expected = page.total; if(page.total !== expected) throw new Error("Records changed during export. Please retry for a consistent workbook."); if(exported + page.total > 50000) throw new Error("This export exceeds 50,000 records. Export one table with a narrower date range."); for(const row of page.rows) { if(seen.has(String(row.id))) throw new Error("Records changed during export. Please retry."); seen.add(String(row.id)); } result.push(...page.rows); setExportProgress(`${item.short}: ${result.length.toLocaleString()} / ${page.total.toLocaleString()} records`); if(!page.hasMore) break; if(!page.rows.length) throw new Error("The export stopped before all records loaded. Please retry."); } }
        exported += result.length; sheets.push({table:item,rows:result});
      } controller.signal.throwIfAborted(); setExportProgress("Writing Excel file…"); await downloadWorkbook(sheets,demo,controller.signal); setNotice(`Prepared ${exported.toLocaleString()} ${demo ? "sample " : ""}records in ${sheets.length} worksheet${sheets.length === 1 ? "" : "s"}. Check your downloads.`); setExportOpen(false);
    } catch(err) { if((err as Error).name !== "AbortError") setError((err as Error).message); } finally { setExportProgress(""); exportAbort.current = null; }
  }
  if(!active) return <main className="admRoot admLogin" data-native-scroll><section className="admLoginStory"><Brand/><div className="admLoginHeadline"><span className="admEyebrow">THE TRUEPRINT WORKSPACE</span><h1>Every enquiry.<br/>One clear view.</h1><p>Bring your leads, catalogue requests and next steps together.</p><div className="admLoginFeatures"><span><Database/>11 connected form tables</span><span><Sparkles/>Smarter follow-ups</span><span><ArrowDownToLine/>Ready-to-use Excel reports</span></div></div><div className="admLoginBottom">PRINT. CONNECT. GROW.</div><span className="admGhost" aria-hidden="true">trueprint</span></section><section className="admLoginPanel"><a href="/" className="admBack"><ArrowLeft size={16}/>Back to website</a><div className="admLoginForm"><div className="admLock"><LockKeyhole size={24}/></div><span className="admEyebrow">ADMIN ACCESS</span><h2>Welcome back.</h2><p>Sign in with your assigned admin account.</p>{!configured && <div className="admInfo"><ShieldCheck size={18}/><span>Live access needs one-time setup. Your admin account and database connection haven’t been configured on this review site.</span></div>}<form onSubmit={signIn}><label>Email address<input type="email" name="email" autoComplete="username" placeholder="you@yourcompany.com" required maxLength={254} disabled={!configured}/></label><label>Password<input type="password" name="password" autoComplete="current-password" placeholder="Enter your password" required maxLength={256} disabled={!configured}/></label>{(error || session.error) && <p role="alert" className="admError">{error || "Unable to check your session. Please retry."}</p>}<button className="admPrimary" disabled={!configured || loginBusy || session.isFetching}>{loginBusy || session.isFetching ? <LoaderCircle className="admSpin" size={17}/> : <LockKeyhole size={17}/>}Sign in to workspace</button></form>{demoEnabled && <><div className="admDivider"><span>EXPLORE THE PREVIEW</span></div><button className="admSecondary admFull" onClick={() => {setSampleRows(demoRecords());setDemo(true);setError("");}}><LayoutDashboard size={18}/>Open sample dashboard<ArrowUpRight size={16}/></button><small className="admMuted">Fictional data only. No customer records or live changes.</small></>}<p className="admLoginNote"><ShieldCheck size={14}/>Restricted to approved TruePrint administrators.</p></div></section></main>;
  return <div className="admRoot admWorkspace" data-native-scroll>{menu && <button className="admNavBackdrop" onClick={() => setMenu(false)} aria-label="Close navigation"/>}<aside className={`admSidebar ${menu ? "isOpen" : ""}`}><Brand/><div className="admWorkspaceLabel"><span className="admWorkspaceIcon"><LayoutDashboard size={18}/></span><span>Admin workspace<small>{demo ? "Sample environment" : "Private workspace"}</small></span></div><div className="admNavLabel">FORM SUBMISSIONS</div><nav aria-label="Admin data tables">{ADMIN_TABLES.map((item,i) => <div key={item.key}>{i === 3 && <div className="admNavLabel admCatalogueLabel">CATALOGUE DOWNLOADS</div>}<button onClick={() => changeTable(item.key)} className={item.key === tableKey ? "isActive" : ""} aria-current={item.key === tableKey ? "page" : undefined}>{i < 3 ? <FileText size={17}/> : <span className="admNavDot"/>}<span>{item.short}</span><small>{counts.find(c => c.key === item.key)?.total?.toLocaleString() ?? "—"}</small></button></div>)}</nav><div className="admSidebarBottom"><button onClick={() => setHelp(true)}><CircleHelp size={17}/>Workspace guide</button><a href="/" target="_blank" rel="noreferrer"><ArrowUpRight size={17}/>View website</a><div className="admUser"><span className="admAvatar">{demo ? "TP" : String(user?.email || "A").slice(0,2).toUpperCase()}</span><span><strong>{demo ? "Preview admin" : "Administrator"}</strong><small>{demo ? "Sample data" : user?.email}</small></span><button onClick={signOut} aria-label={demo ? "Exit sample dashboard" : "Sign out"}><LogOut size={17}/></button></div></div></aside>
    <div className="admMain"><header className="admTopbar"><div><button className="admIcon admMobileMenu" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu size={21}/></button><span className="admBreadcrumb">Workspace<ChevronRight size={13}/><strong>{table.short}</strong></span></div><span className={`admConnection ${demo ? "isDemo" : ""}`}><i/>{demo ? "Sample preview" : "Authenticated session"}</span></header><main className="admContent">{demo && <div className="admDemoBanner"><span><ShieldCheck size={17}/><strong>Sample workspace</strong> · All records are fictional. Changes reset when you leave.</span><button onClick={signOut}>Go to login<ArrowUpRight size={14}/></button></div>}
    <div className="admPageTitle"><div><span className="admEyebrow">YOUR ENQUIRIES, ORGANIZED</span><h1>{table.label}</h1><p>{table.kind === "catalogue" ? "Everyone who requested this collection, ready for your next conversation." : "Review requirements, find the right opportunities and keep things moving."}</p></div><div className="admTitleActions"><button className="admSecondary" onClick={() => {setError("");if(demo) setNotice("Sample records are up to date.");else {void records.refetch();void overview.refetch();}}} disabled={busy}><RefreshCw size={16} className={busy ? "admSpin" : ""}/>Refresh</button><button className="admPrimary" onClick={() => setExportOpen(true)} disabled={!!exportProgress}><ArrowDownToLine size={17}/>Export Excel</button></div></div>
    <section className="admMetrics" aria-label="Workspace totals"><div><span>All form records<Database size={16}/></span><strong>{available ? allCount.toLocaleString() : "—"}</strong><small>{available < 11 ? `${available} of 11 tables available` : "Across all 11 tables"}</small></div><div><span>Matching records<Filter size={16}/></span><strong>{busy ? "…" : total.toLocaleString()}</strong><small>Current table and filters</small></div><div><span>To review on this page<Users size={16}/></span><strong>{busy ? "…" : pending}</strong><small>New or incomplete submissions</small></div></section>
    <section className="admAssistant"><div className="admAssistantIntro"><span className="admSpark"><Sparkles size={20}/></span><div><h2>A little help finding the right lead.</h2><p>Try a plain-language filter. Local rules, no external AI service.</p></div></div><form onSubmit={e => {e.preventDefault();applyAssistant();}}><Search size={17}/><input aria-label="Smart filter" value={assistant} onChange={e => setAssistant(e.target.value)} placeholder='Try “new pens last 7 days”' maxLength={200}/><button type="submit" aria-label="Apply smart filter"><ArrowUpRight size={19}/></button></form><div className="admPrompts">{["New projects last 7 days","New contacts today","Qualified diaries"].map(text => <button key={text} onClick={() => {setAssistant(text);applyAssistant(text);}}>{text}<ArrowUpRight size={12}/></button>)}</div></section>
    {notice && <div className="admNotice" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={() => setNotice("")}><X size={15}/></button></div>}{(error || records.error || overview.error) && <div className="admError" role="alert">{error || (records.error || overview.error)?.message}<button onClick={() => {setError("");void records.refetch();void overview.refetch();}}>Retry</button></div>}{!demo && counts.some(c => c.error) && <p className="admError">Some tables could not be loaded. Their counts are excluded; select a table and refresh to retry.</p>}
    <section className="admDataPanel" aria-label="Records"><div className="admTableToolbar"><div className="admTabs" aria-label="Quick status filters">{["","new",...(table.statuses.includes("qualified") ? ["qualified"] : []),"closed"].map(status => <button key={status} className={filters.status === status ? "isActive" : ""} onClick={() => changeFilter({status})}>{status ? fieldLabel(status) : "All records"}</button>)}</div><details className="admColumns"><summary><Columns3 size={15}/>Columns</summary><div>{grid.getAllLeafColumns().filter(c => c.getCanHide()).map(column => <label key={column.id}><input type="checkbox" checked={column.getIsVisible()} onChange={column.getToggleVisibilityHandler()}/>{typeof column.columnDef.header === "string" ? column.columnDef.header : fieldLabel(column.id)}</label>)}</div></details></div>
    <div className="admFilters"><label className="admSearch"><Search size={17}/><input aria-label="Search records" placeholder="Search name, email, phone or requirement…" value={search} maxLength={160} onChange={e => setSearch(e.target.value)}/></label><label>Status<select value={filters.status} onChange={e => changeFilter({status:e.target.value})}><option value="">All statuses</option>{table.statuses.map(s => <option key={s} value={s}>{fieldLabel(s)}</option>)}</select></label><label>From · UTC<input type="date" aria-label="From date" value={filters.from} max={filters.to || undefined} onChange={e => changeFilter({from:e.target.value})}/></label><label>To · UTC<input type="date" aria-label="To date" value={filters.to} min={filters.from || undefined} onChange={e => changeFilter({to:e.target.value})}/></label><button className="admTextButton" onClick={() => {setSearch("");setFilters({...EMPTY_FILTERS});setPagination(p => ({...p,pageIndex:0}));}}>Reset</button></div>
    <div className="admResultLine"><span>{grid.getSelectedRowModel().rows.length ? `${grid.getSelectedRowModel().rows.length} selected on this page` : `${total.toLocaleString()} matching records`}</span><label>Sort<select aria-label="Sort records" value={filters.sort} onChange={e => changeFilter({sort:e.target.value as AdminFilters["sort"]})}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div>
    <div className="admTableScroll" aria-busy={busy}><table><thead>{grid.getHeaderGroups().map(group => <tr key={group.id}>{group.headers.map(header => <th key={header.id}>{header.isPlaceholder ? null : flexRender(header.column.columnDef.header,header.getContext())}</th>)}</tr>)}</thead><tbody>{!busy && grid.getRowModel().rows.map(row => <tr key={row.id} className={row.getIsSelected() ? "isSelected" : ""}>{row.getVisibleCells().map(cell => <td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table>{busy ? <div className="admEmpty"><LoaderCircle className="admSpin"/><h3>Loading records…</h3></div> : !rows.length && <div className="admEmpty"><Search size={28}/><h3>{records.isError ? "Records are unavailable" : "No matching records"}</h3><p>{records.isError ? "Use Refresh to try again." : "Try another search, date range or table."}</p></div>}</div>
    <div className="admPagination"><span>{total ? `${pagination.pageIndex * pagination.pageSize + 1}–${Math.min((pagination.pageIndex + 1) * pagination.pageSize,total)} of ${total.toLocaleString()}` : "0 records"}</span><div><label>Rows<select aria-label="Rows per page" value={pagination.pageSize} onChange={e => setPagination({pageIndex:0,pageSize:Number(e.target.value)})}>{[25,50,100].map(n => <option key={n}>{n}</option>)}</select></label><button className="admIcon" aria-label="Previous page" disabled={!grid.getCanPreviousPage() || busy} onClick={() => grid.previousPage()}><ChevronLeft size={18}/></button><span>{pagination.pageIndex+1} / {Math.max(1,grid.getPageCount())}</span><button className="admIcon" aria-label="Next page" disabled={!grid.getCanNextPage() || busy} onClick={() => grid.nextPage()}><ChevronRight size={18}/></button></div></div></section><p className="admBottomNote"><ShieldCheck size={13}/>{demo ? "Sample data stays in this browser session." : "Private records. Sign out when you finish on a shared device."}<span>TRUEPRINT / ADMIN</span></p></main></div>
    {detail && <RecordDetail key={String(detail.id)} row={detail} table={table} demo={demo} duplicates={rows.filter(r => r.email === detail.email && r.id !== detail.id).length} onClose={() => setDetail(null)} onSaved={updated => {setDetail(updated);if(demo) setSampleRows(current => ({...current,[tableKey]:current[tableKey].map(row => row.id === updated.id ? updated : row)}));else void client.invalidateQueries({queryKey:["admin-records"]});setNotice(demo ? "Sample status updated for this session." : "Record status saved.");}}/>}
    {exportOpen && <Modal title="Export to Excel" onClose={() => {if(exportProgress) exportAbort.current?.abort();setExportOpen(false);}}><p className="admModalCopy">Choose the records to include. Each table gets its own worksheet. Exports include every permitted data column.</p><div className="admExportChoices"><button disabled={!!exportProgress || !grid.getSelectedRowModel().rows.length} onClick={() => exportData("selected")}><Users/><span><strong>Selected records</strong><small>{grid.getSelectedRowModel().rows.length} selected on this page</small></span><ArrowDownToLine/></button><button disabled={!!exportProgress} onClick={() => exportData("filtered")}><Filter/><span><strong>Current filtered table</strong><small>{total.toLocaleString()} matching records, across every page</small></span><ArrowDownToLine/></button><button disabled={!!exportProgress} onClick={() => exportData("all")}><Database/><span><strong>All 11 tables</strong><small>Includes all records; ignores the current filters</small></span><ArrowDownToLine/></button></div><p className="admMuted">Up to 50,000 records per workbook. Large datasets can be split with date filters. {demo && "This download contains fictional sample data."}</p>{error && <p className="admError" role="alert">{error}</p>}{exportProgress && <div className="admNotice" role="status"><LoaderCircle className="admSpin" size={16}/>{exportProgress}<button onClick={() => exportAbort.current?.abort()}>Cancel</button></div>}</Modal>}
    {help && <Modal title="Your workspace guide" onClose={() => setHelp(false)}><div className="admHelp"><h3>Find a submission</h3><p>Choose any of the 11 tables. Search contacts and requirements, filter by status or UTC dates, and sort oldest or newest first.</p><h3>Review and follow up</h3><p>Open a contact to inspect every saved field, download an attachment, change its status or prepare a reply. Incomplete intakes can only be completed by the visitor.</p><h3>Smart assistance</h3><p>Filters, briefs and reply drafts use local rules, not a generative AI model. Review drafts yourself; no message is sent automatically.</p><h3>Export records</h3><p>Export selected current-page rows, every matching record across pages, or all 11 tables. Form tokens, passwords and service keys are never included.</p><h3>Admin access</h3><p>Use a pre-created Supabase Auth account with its user ID in the server’s TRUEPRINT_ADMIN_USER_IDS setting. See ADMIN_SETUP.md for setup. Sign-in is required again within one hour.</p></div></Modal>}
  </div>;
}
function RecordDetail({row,table,demo,duplicates,onClose,onSaved}:{row:AdminRow;table:AdminTable;demo:boolean;duplicates:number;onClose:()=>void;onSaved:(row:AdminRow)=>void}) {
  const [status,setStatus] = useState(String(row.status)); const [saving,setSaving] = useState(false); const [error,setError] = useState(""); const brief = leadBrief(row,table); const [draft,setDraft] = useState(brief.draft); const [copied,setCopied] = useState(false); const incomplete = table.kind === "intake" && row.completion_status !== "complete";
  async function save() {setSaving(true);setError("");try {const updated = demo ? {...row,status} : (await api<{row:AdminRow}>("records",{method:"PATCH",body:JSON.stringify({table:table.key,id:row.id,status,previousStatus:row.status})})).row;onSaved(updated);}catch(err){setError((err as Error).message);}finally{setSaving(false);}}
  async function copy(){try{await navigator.clipboard.writeText(draft);setCopied(true);}catch{setError("Copy is unavailable here. Select and copy the draft manually.");}}
  return <Modal title="Record details" drawer onClose={onClose}><div className="admDetailPerson"><span className="admAvatar">{String(row.name).split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><h3>{display(row.name)}</h3><p>{display(row.organization || table.label)}</p></div><Status value={row.status}/></div><div className="admDetailLinks"><a href={`mailto:${encodeURIComponent(String(row.email || ""))}`}><Mail size={15}/>{display(row.email)}</a><span>{display(row.phone)}</span></div><div className="admStatusEditor"><label>Record status<select value={status} onChange={e=>setStatus(e.target.value)} disabled={incomplete || saving}>{table.statuses.filter(s=>s!=="incomplete" || incomplete).map(s=><option key={s} value={s}>{fieldLabel(s)}</option>)}</select></label><button className="admPrimary" disabled={incomplete || saving || status===row.status} onClick={save}>{saving?<LoaderCircle size={16} className="admSpin"/>:<Check size={16}/>}Save status</button></div>{incomplete&&<p className="admMuted">Step two is incomplete. Completion and consent can only be provided by the visitor.</p>}{error&&<p className="admError" role="alert">{error}</p>}<section className="admBrief"><h3><Sparkles size={18}/>Lead brief<small>LOCAL RULES</small></h3><p>{brief.summary}</p><div><strong>Suggested next step</strong><p>{brief.next}</p></div>{duplicates>0&&<p className="admDuplicate">{duplicates} other record{duplicates>1?"s":""} with this email on the current page. Review before contacting twice.</p>}</section><section className="admDraft"><h3>Reply draft<span>Review before using</span></h3><textarea aria-label="Editable reply draft" value={draft} onChange={e=>{setDraft(e.target.value);setCopied(false);}} rows={9}/><div><button className="admSecondary" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?"Copied":"Copy draft"}</button><button className="admTextButton" onClick={()=>{setDraft(brief.draft);setCopied(false);}}>Reset draft</button></div><small>No message is sent from this dashboard.</small></section><h3 className="admDetailsTitle">All saved fields</h3><dl className="admFieldList">{table.columns.map(key=><div key={key}><dt>{fieldLabel(key)}</dt><dd>{display(row[key])}</dd></div>)}</dl>{row.reference_file_path&&!demo&&<a className="admSecondary admAttachment" href={`/api/admin/attachment?${new URLSearchParams({table:table.key,id:String(row.id)})}`}><ArrowDownToLine size={16}/>Download attachment</a>}</Modal>;
}
