import { ADMIN_TABLES, findAdminTable, type AdminRow, type AdminTable } from "../admin/schema";
import { AdminError } from "./admin-auth";
import { getSupabaseConfig } from "./supabase-config";
export function selectedTable(params: URLSearchParams): AdminTable { const table = findAdminTable(params.get("table")); if (!table) throw new AdminError("Choose a valid form table.", 400); return table; }
function numberParam(params: URLSearchParams, key: string, fallback: number, max: number) { if (!params.has(key)) return fallback; const value = Number(params.get(key)); if (!Number.isSafeInteger(value) || value < 0 || value > max) throw new AdminError(`Invalid ${key}.`, 400); return value; }
function day(value: string | null) { if (!value) return ""; if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || !Number.isFinite(Date.parse(value)) || new Date(value).toISOString().slice(0, 10) !== value) throw new AdminError("Choose a valid date range.", 400); return value; }
export function recordsQuery(table: AdminTable, params: URLSearchParams) {
  const query = new URLSearchParams({ select: table.columns.join(",") }); const offset = numberParam(params, "offset", 0, 1_000_000); const limit = numberParam(params, "limit", 25, 500); if (!limit) throw new AdminError("Invalid limit.", 400);
  query.set("offset", String(offset)); query.set("limit", String(limit)); const sort = params.get("sort") || "newest"; if (!["newest", "oldest"].includes(sort)) throw new AdminError("Invalid sort order.", 400); const direction = sort === "oldest" ? "asc" : "desc"; query.set("order", `${table.date}.${direction},id.${direction}`);
  const status = params.get("status"); if (status) { if (!table.statuses.includes(status)) throw new AdminError("Invalid status for this table.", 400); query.set("status", `eq.${status}`); }
  const from = day(params.get("from")); const to = day(params.get("to")); if (from && to && from > to) throw new AdminError("The start date must be before the end date.", 400); if (from) query.append(table.date, `gte.${from}T00:00:00.000Z`); if (to) query.append(table.date, `lt.${new Date(Date.parse(to) + 86400000).toISOString()}`);
  const before = params.get("before"); if (before) { if (!/^\d{4}-\d{2}-\d{2}T[\d:.]+Z$/.test(before) || !Number.isFinite(Date.parse(before))) throw new AdminError("Invalid export time.", 400); query.append(table.date, `lte.${before}`); }
  const search = (params.get("search") || "").trim(); if (search.length > 160) throw new AdminError("Search must be 160 characters or less.", 400);
  if (search) { const escaped = search.replace(/[\\%_*]/g, "\\$&").replace(/"/g, '\\"'); query.set("or", `(${table.search.map(field => `${field}.ilike."%${escaped}%"`).join(",")})`); }
  return { query, offset };
}
export async function databaseRequest(table: AdminTable, query: URLSearchParams, init: RequestInit = {}) { const config = getSupabaseConfig(); const response = await fetch(`${config.url}/rest/v1/${table.key}?${query}`, { ...init, headers: { apikey: config.serviceRoleKey, authorization: `Bearer ${config.serviceRoleKey}`, prefer: "count=exact", ...init.headers }, cache: "no-store", signal: AbortSignal.timeout(15_000) }); if (!response.ok) throw new AdminError(response.status === 404 ? `${table.label} is not available in this database. Check its setup script.` : `Unable to load ${table.label.toLowerCase()}. Please retry.`, 502); return response; }
function safeRow(table: AdminTable, row: AdminRow): AdminRow { return Object.fromEntries(table.columns.map(key => [key, row[key] ?? null])); }
export async function getRecords(params: URLSearchParams) { const table = selectedTable(params); const { query, offset } = recordsQuery(table, params); const response = await databaseRequest(table, query); const count = response.headers.get("content-range")?.split("/")[1]; if (!count || !/^\d+$/.test(count)) throw new AdminError("The database did not return a record count. Please retry.", 502); const rows = (await response.json() as AdminRow[]).map(row => safeRow(table, row)); const total = Number(count); return { rows, total, offset, hasMore: offset + rows.length < total }; }
export async function getOverview() { return Promise.all(ADMIN_TABLES.map(async table => { try { const response = await databaseRequest(table, new URLSearchParams({ select: "id", limit: "1" }), { method: "HEAD" }); const count = response.headers.get("content-range")?.split("/")[1]; if (!count || !/^\d+$/.test(count)) throw new Error("Missing count"); return { key: table.key, total: Number(count), error: null }; } catch { return { key: table.key, total: null, error: "Unavailable" }; } })); }
export async function recordById(table: AdminTable, id: unknown) { if (typeof id !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) throw new AdminError("Invalid record ID.", 400); const response = await databaseRequest(table, new URLSearchParams({ select: table.columns.join(","), id: `eq.${id}`, limit: "1" })); const row = (await response.json() as AdminRow[])[0]; if (!row) throw new AdminError("This record is no longer available.", 404); return safeRow(table, row); }
export async function changeStatus(body: Record<string, unknown>) { const table = findAdminTable(typeof body.table === "string" ? body.table : ""); if (!table || typeof body.status !== "string" || !table.statuses.includes(body.status) || body.status === "incomplete" || typeof body.previousStatus !== "string" || !table.statuses.includes(body.previousStatus)) throw new AdminError("Invalid status update.", 400); const row = await recordById(table, body.id); if (table.kind === "intake" && row.completion_status !== "complete") throw new AdminError("This visitor has not completed step two. Its intake status cannot be changed here.", 409); const response = await databaseRequest(table, new URLSearchParams({ select: table.columns.join(","), id: `eq.${row.id}`, status: `eq.${body.previousStatus}` }), { method: "PATCH", headers: { "content-type": "application/json", prefer: "return=representation" }, body: JSON.stringify({ status: body.status }) }); const updated = (await response.json() as AdminRow[])[0]; if (!updated) throw new AdminError("This record changed elsewhere. Refresh before saving again.", 409); return safeRow(table, updated); }
