import { ADMIN_TABLES, EMPTY_FILTERS, type AdminFilters, type AdminRow, type AdminTable } from "./schema";
/** Explainable local assistance; no customer data is sent to an AI provider. */
export function leadBrief(row: AdminRow, table: AdminTable) {
  const requirement = String(row.requirement || row.catalogue_title || ""); const quantity = Number(row.estimated_quantity) || null;
  const urgent = /\b(urgent|asap|immediately|tomorrow|this week)\b/i.test(requirement);
  const missing = table.kind === "catalogue" ? ["quantity", "branding requirements", "delivery date"] : [!quantity && "quantity", !/(?:\b(?:budget|rs\.?|inr)\b|₹)/i.test(requirement) && "budget", !/\b(deliver|delivery|deadline|date|week|month|tomorrow)\b/i.test(requirement) && "delivery date"].filter(Boolean) as string[];
  const summary = table.kind === "catalogue" ? `${row.name} requested ${row.catalogue_title || table.short}. Their saved status is ${row.status}.` : `${row.name}${row.organization ? ` from ${row.organization}` : ""} requested: ${requirement || "No requirement provided"}${quantity ? ` Quantity: ${quantity.toLocaleString("en-IN")}.` : ""}`;
  const next = row.status === "closed" || row.status === "spam" ? "This record is closed or marked as spam. Review before contacting." : row.completion_status === "incomplete" ? "Step two is incomplete. Review the saved requirement before following up; no final consent was captured." : urgent ? "The requirement contains urgent timing language. Confirm the deadline before promising availability." : missing.length ? `Clarify ${missing.join(", ")} before preparing a quote.` : "Review the requirement and prepare a personalised follow-up.";
  const draft = `Hi ${String(row.name || "there").split(" ")[0]},\n\nThank you for contacting TruePrint about ${table.kind === "catalogue" ? `your ${table.short.toLowerCase()} catalogue request` : "your printing requirement"}.${row.catalogue_title ? ` We have received your interest in ${row.catalogue_title}.` : ""}\n\n${missing.length ? `Could you share your ${missing.join(", ")} so we can recommend suitable options?` : "We would be happy to discuss the specifications and next steps with you."}\n\n${urgent ? "Please also confirm your required delivery date so we can check feasibility.\n\n" : ""}Best regards,\nTeam TruePrint`;
  return { summary, next, draft, urgent, missing, quantity };
}
export function smartFilter(input: string, now = new Date()): { table?: string; filters: AdminFilters; explanation: string } {
  let remaining = input.toLowerCase().trim(); const filters = { ...EMPTY_FILTERS };
  const aliases: [string, string][] = [["project intakes", "homepage_project_intakes"], ["projects", "homepage_project_intakes"], ["contact enquiries", "contact_enquiries"], ["contacts", "contact_enquiries"], ["sourcing", "source_requests"], ["visiting cards", "visiting_cards_catalogue_downloads"], ["joining kits", "joining_kits_catalogue_downloads"], ["tech products", "tech_products_catalogue_downloads"], ["t-shirts", "t_shirts_catalogue_downloads"], ["diaries", "diary_catalogue_downloads"], ["pens", "pens_catalogue_downloads"], ["bags", "bags_catalogue_downloads"], ["drinkware", "drinkware_catalogue_downloads"]];
  let table: string | undefined; for (const [word, key] of aliases) if (remaining.includes(word)) { table = key; remaining = remaining.replace(word, ""); break; }
  const status = remaining.match(/\b(incomplete|new|contacted|qualified|closed|spam|reviewing|sourced)\b/); if (status) { filters.status = status[1]; remaining = remaining.replace(status[0], ""); }
  const period = remaining.match(/\b(today|this week|last (\d{1,3}) days)\b/); if (period) { const days = period[1] === "today" ? 1 : period[1] === "this week" ? 7 : Math.max(1, Number(period[2])); filters.to = now.toISOString().slice(0, 10); filters.from = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()) - (days - 1) * 86400000).toISOString().slice(0, 10); remaining = remaining.replace(period[0], ""); }
  filters.search = remaining.replace(/\b(show|me|all|leads|records|from|for|in|the|catalogues|catalogue)\b/g, " ").replace(/\s+/g, " ").trim().slice(0, 160);
  return { table, filters, explanation: [ADMIN_TABLES.find(item => item.key === table)?.label, filters.status && `Status: ${filters.status}`, filters.from && `${filters.from} to ${filters.to} (UTC)`, filters.search && `Search: ${filters.search}`].filter(Boolean).join(" · ") || "Showing all records in the selected table." };
}
